FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git \
    && git clone https://github.com/Nerimity/nerimity-server.git . \
    && npm install --legacy-peer-deps

EXPOSE 3001
CMD ["npm", "start"]
