FROM node:20-alpine

WORKDIR /app

# Gerekli paketler
RUN apk add --no-cache git

# Kodu indir
RUN git clone https://github.com/Nerimity/nerimity-server.git .

# Node modülleri kur (peer dep hatalarına izin veriyoruz)
RUN npm install --legacy-peer-deps

# Typescript derleyicisi ve ts-node gerekiyor
RUN npm install -g ts-node typescript

EXPOSE 3001

CMD ["npm", "run", "dev"]
