FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

RUN apk add --no-cache git && \
    git clone https://github.com/Nerimity/nerimity-web.git . 

RUN pnpm install
RUN pnpm build

EXPOSE 3000
CMD ["pnpm", "preview"]
