FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git openssl

# PNPM kur
RUN npm install -g pnpm

# Repo klonla
RUN git clone https://github.com/Nerimity/nerimity-server.git .

# Bağımlılıkları yükle
RUN pnpm install

# Prisma Client'ı oluştur
RUN pnpm prisma generate

# Build aşaması
RUN pnpm build

EXPOSE 3001

CMD ["pnpm", "start"]
