FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git \
    && git clone https://github.com/Nerimity/nerimity-web.git . \
    && npm install --legacy-peer-deps \
    && npm run build

EXPOSE 3000
CMD ["npm", "run", "preview"]
